//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReserveApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Id { get; set; }
        public int ClassroomId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        public int LessonNumber { get; set; }
        public Nullable<int> StudentsCount { get; set; }
        public int GroupId { get; set; }
        public int StatusId { get; set; }
        public string Lesson { get; set; }
        public string Comment { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Group Group { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
